server:
  port: 8489
spring:
  application:
    name: CONFIG
    cloud:
      consul:
        host: localhost  #服务注册地址  如果装在linux上 则是ip
        port: 8500
        discovery:
          service-name: {spring.application.name}  #指定注册当前服务的服务名称 默认{spring.application.name}
          heartbeat:
            enabled: true #开启心跳检查
